---
# tasks file for ansible-role-basic-apache-container
- include_tasks: "setup-centos.yml" #lancement du fichier de paramettrage de la vm
- include_tasks: "install-docker.yml" #lancement du fichier d'installation de docker;dockercompose
- name: Copy website file template
  template:
    src: "{{ file_template }}"
    dest: "/home/{{ system_user }}/index.html"
- name: Create Apache container #creation du conteneur Apache
  docker_container: #utilisation du module pour lancer le conteneur Apache
    name: webapp
    image: httpd
    ports:
        - "{{ webapp_port }}:{{ apache_port }}"
    volumes:
        - "/home/{{ system_user }}/index.html:/usr/local/apache2/htdocs/index.html"